collections:
  games:
    output: true

defaults:
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  - scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/images/logo/overcade-logo-with-text.png" # image for social sharing preview

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss-v2
  - jekyll-responsive-image

postcss:
  cache: false

responsive_image:
  template: _includes/responsive-image.html.liquid
  save_to_source: false
  sizes:
    - width: 80
    - width: 160
    - width: 320
    - width: 480
    - width: 800
    - width: 1000
    - width: 1200
    - width: 1500
    - width: 2000
  extra_images:
    - assets/images/pac-man-in-office.JPG

# SEO
title: Overcade arcadeverhuur
tagline: Authentiek arcadeverhuur
description: Verhuur van authentieke arcadekasten voor thuis of op kantoor
url: https://overcade.be
locale: nl_BE
logo: /assets/images/logo/overcade-logo-with-text.png
social:
  name: Overcade
  links:
    - https://www.facebook.com/overcade
    - https://www.instagram.com/overcade.be

