collections:
  games:
    output: true

defaults:
  - scope:
      path: ""
      type: "games"
    values:
      layout: "game"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postcss-v2
  - jekyll-responsive-image

postcss:
  cache: false

responsive_image:
  template: _includes/responsive-image.html.liquid
  save_to_source: false
  sizes:
    - width: 160
    - width: 320
    - width: 480
    - width: 800
    - width: 1000
    - width: 1200
    - width: 1500